### ISSUE TITLE
[QUESTION] checkIntermittentProducerCallback(): operation returned status code: 0x52000084

### ISSUE THREAD

**Issue by Nomidia** [awslabs/amazon-kinesis-video-streams-pic#106] opened 2021-01-04 08:29 UTC
Continuous printing after pausing to put frames.

```
2021-01-04 08:26:02 DEBUG   postReadCallback(): Wrote 16372 bytes to Kinesis Video. Upload stream handle: 0
2021-01-04 08:26:02 DEBUG   postReadCallback(): Wrote 16372 bytes to Kinesis Video. Upload stream handle: 0
2021-01-04 08:26:02 DEBUG   postReadCallback(): Wrote 16372 bytes to Kinesis Video. Upload stream handle: 0
2021-01-04 08:26:02 DEBUG   postReadCallback(): Wrote 16372 bytes to Kinesis Video. Upload stream handle: 0
2021-01-04 08:26:02 DEBUG   postReadCallback(): Wrote 7939 bytes to Kinesis Video. Upload stream handle: 0
2021-01-04 08:26:02 DEBUG   postReadCallback(): Pausing CURL read for upload handle: 0
pKinesisVideoStream->streamInfo.streamCaps.frameOrderingMode=3, pFrameOrderCoordinator->keyFrameDetected=1
2021-01-04 08:26:20 WARN    putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000084 decoding timestamp: 0 presentation timestamp: 0
2021-01-04 08:26:20 WARN    checkIntermittentProducerCallback(): Failed to submit auto eofr with 0x52000084, for stream name: UB3Ve2Pc2P3S3
2021-01-04 08:26:20 ERROR   checkIntermittentProducerCallback(): operation returned status code: 0x52000084
2021-01-04 08:26:20 ERROR   timerQueueExecutor(): operation returned status code: 0x52000084
pKinesisVideoStream->streamInfo.streamCaps.frameOrderingMode=3, pFrameOrderCoordinator->keyFrameDetected=1
2021-01-04 08:26:25 WARN    putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000084 decoding timestamp: 0 presentation timestamp: 0
2021-01-04 08:26:25 WARN    checkIntermittentProducerCallback(): Failed to submit auto eofr with 0x52000084, for stream name: UB3Ve2Pc2P3S3
2021-01-04 08:26:25 ERROR   checkIntermittentProducerCallback(): operation returned status code: 0x52000084
2021-01-04 08:26:25 ERROR   timerQueueExecutor(): operation returned status code: 0x52000084


pKinesisVideoStream->streamInfo.streamCaps.frameOrderingMode=3, pFrameOrderCoordinator->keyFrameDetected=1
2021-01-04 08:26:30 WARN    putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000084 decoding timestamp: 0 presentation timestamp: 0
2021-01-04 08:26:30 WARN    checkIntermittentProducerCallback(): Failed to submit auto eofr with 0x52000084, for stream name: UB3Ve2Pc2P3S3
2021-01-04 08:26:30 ERROR   checkIntermittentProducerCallback(): operation returned status code: 0x52000084
2021-01-04 08:26:30 ERROR   timerQueueExecutor(): operation returned status code: 0x52000084


pKinesisVideoStream->streamInfo.streamCaps.frameOrderingMode=3, pFrameOrderCoordinator->keyFrameDetected=1
2021-01-04 08:26:35 WARN    putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x52000084 decoding timestamp: 0 presentation timestamp: 0
```

**Comment by hassanctech** [comment] 2021-01-04 11:48
It looks like you're using a fairly recent commit, we have just added functionality to automatically handle intermittent producer scenarios (where you might stop sending frames for some period of time and then resume).  Can you please make sure you have the very latest changes, commit: d580ad84fb6e1de6fe131ccb7bc575e17051bea6

Also, are you using PIC directly or the producer c library?  If you're using PIC directly, are you attempting to manually submit EOFR frames?  If so, please stop as it will conflict with this new functionality.  If you continue to see errors, and you're not submitting EOFR on your own then please update here.

**Comment by hassanctech** [comment] 2021-01-04 11:50
Ah ok I think I see your iseeue, pelase use the following frameOrderingMode:

    FRAME_ORDERING_MODE_MULTI_TRACK_AV_COMPARE_PTS_ONE_MS_COMPENSATE_EOFR       = 5,

That should solve your problem.

**Comment by Nomidia** [comment] 2021-01-04 12:09
It's the latest code and I am using the c-producer samples to test.

**Comment by hassanctech** [comment] 2021-01-05 00:38
If your issue is resolved, please closed the ticket.  Thank you.

**Comment by Nomidia** [comment] 2021-01-05 01:23
After changing the frameOrderMode, another error is returned.
```
2021-01-05 01:09:20 ERROR   checkIntermittentProducerCallback(): operation returned status code: 0x30000003
2021-01-05 01:09:20 ERROR   timerQueueExecutor(): operation returned status code: 0x30000003
pKinesisVideoStream->streamInfo.streamCaps.frameOrderingMode=5, pFrameOrderCoordinator->keyFrameDetected=1
2021-01-05 01:09:26 WARN    putKinesisVideoFrame(): Failed to submit frame to Kinesis Video client. status: 0x30000003 decoding timestamp: 0 presentation timestamp: 0
2021-01-05 01:09:26 WARN    checkIntermittentProducerCallback(): Failed to submit auto eofr with 0x30000003, for stream name: UB3Ve2Pc2P3S3
```

**Comment by hassanctech** [comment] 2021-01-05 01:43
Currently, we stop and reset the stream every motion detection occurs. << You do not need to do this any more.  Now intermittent producer scenario is automatically handled.  You no longer have to do stop or reset.  Please try again after you remove the stop/reset. Please be aware our automatic intermittent producer implementation (which is enabled by default) creates 1 separate thread to handle this, if you're on an embedded device where this is of concern then you can disable this functionality and everything will work as is, to do that set:

pKinesisVideoClient->deviceInfo.clientInfo.automaticStreamingFlags = AUTOMATIC_STREAMING_ALWAYS_CONTINUOUS

But I would not do this unless you have concerns about the extra thread being created.

**Comment by Nomidia** [comment] 2021-01-05 01:52
For this issue, I am just using the sample in producer-c. After pausing to put frames for a while, the printing occurs. In KvsAacAudioVideoStreamingSample, I did not stop and reset stream. My purpose is to check your new feature about intermittent producer.

**Comment by MushMal** [comment] 2021-01-05 02:21
@hassanctech do you have a repro case with the view returning STATUS_CONTENT_VIEW_NO_MORE_ITEMS? I am not sure what's in the timer callback can return this? @Nomidia what's the repro step for this?

**Comment by Nomidia** [comment] 2021-01-05 02:31
> Ah ok I see your issue, please use the following frameOrderingMode:
> 
> ```
> FRAME_ORDERING_MODE_MULTI_TRACK_AV_COMPARE_PTS_ONE_MS_COMPENSATE_EOFR       = 5,
> ```
> 
> That should solve your problem.

I change the frame order mode to FRAME_ORDERING_MODE_MULTI_TRACK_AV_COMPARE_PTS_ONE_MS_COMPENSATE_EOFR. 
I added a sleep to simulate pausing to put frames.
```
    THREAD_JOIN(videoSendTid, NULL);
    THREAD_JOIN(audioSendTid, NULL);

    sleep(40);
    CHK_STATUS(stopKinesisVideoStreamSync(streamHandle));
```

**Comment by MushMal** [comment] 2021-01-05 02:35
This output makes no sense to me

```
2021-01-05 01:09:20 ERROR   checkIntermittentProducerCallback(): operation returned status code: 0x30000003
2021-01-05 01:09:20 ERROR   timerQueueExecutor(): operation returned status code: 0x30000003

```

I will let @hassanctech to comment

**Comment by MushMal** [comment] 2021-01-06 05:04
The root cause of the 0x300..03 is merged. There is another minor fix in flight which should land shortly. Please check if you have any issues and cut a separate issue if you do. Please go ahead and fix this.

**Comment by Nomidia** [comment] 2021-01-06 07:44
0x30000003 is resolved, at the same time, frame order mode in c-producer needs to be mmodified.
```
    // use relative time mode. Buffer timestamps start from 0
    pStreamInfo->streamCaps.absoluteFragmentTimes = FALSE;

    pStreamInfo->streamCaps.frameOrderingMode = FRAME_ORDERING_MODE_MULTI_TRACK_AV_COMPARE_PTS_ONE_MS_COMPENSATE_EOFR;

```

**Comment by MushMal** [comment] 2021-01-06 07:53
Yep, I believe @hassanctech will follow up with the c producer fixes

**Closed** 2021-01-06 08:07 UTC
Labels: question
